---
- name: filter ipv4
  gather_facts: false
  hosts: cs01
  roles:
    - new_role


  tasks:
    - name: run a command
      ios_command:
        commands:
          - show interface ethernet eth2
      register: result
      ignore_errors: True

    - debug:
        msg: "show interface ethernet eth2 failed, interface might not be present"
      when: result is failed
