---
- name: test show command
  hosts: cisco_group
  gather_facts: false


  tasks:
    - name: run a command
      ios_command:
        commands:
          - show interfaces gi0/9
      register: result
      ignore_errors: True

    - debug:
        msg: "{{ result }}"
      

    - debug:
        msg: "show interface ethernet {{ interface }} failed, interface might not be present"
      when: result is failed