---
- name: filter ipv4
  gather_facts: false
  hosts: cs01
  roles:
    - new_role2


  tasks:
    - name: Install Role Dependencies
      ansible.builtin.command:
        cmd: ansible-galaxy install --roles-path roles/ -r ./roles/requirements.yml

    - name: run a command
      ios_command:
        commands:
          - show interface ethernet eth2
      register: result
      ignore_errors: True

    - debug:
        msg: "show interface ethernet eth2 failed, interface might not be present"
      when: result is failed
