---
- name: test show command
  hosts: cisco_group
  gather_facts: false


  tasks:
    - name: run a command
      ios_command:
        commands:
          - show interface "{{ interface }}"
      register: result
      ignore_errors: True

    - debug:
        msg: "show interface ethernet eth2 failed, interface might not be present"
      when: result is failed