---
- name: show role path
  hosts: cs01
  gather_facts: true
  roles: 
    - role: "new_role2"
      tags: "role"

  tasks:

    - name: display folder
      ansible.builtin.shell: |
        cd ./roles/new_role2/files
        ls
      register: result

    - debug:
        var: result 

    - name: injection of the configuration
      ios_config:
        src: "{{ lookup('template', './templates/shutdown.j2') }}"
      