---
- name: show interface
  hosts: cs01
  gather_facts: false
  become: yes
  
  tasks:
    - name: show interface of cs01
      ios_command:
        commands: show interfaces {{ interface }}
      register: result

    - debug:
        var: result

    - name: Save variable result to file
      copy:
        content: "{{ result }}"
        dest: "./file/result.txt"
    
    - name: display folder
      ansible.builtin.shell: |
        cd file && ls
      register: result

    - debug:
        var: result     

    - name: Save variable result to file
      ansible.builtin.shell: |
        git config --global user.name "faya97"
        git config --global user.email "chaneric762@gmail.com"
        git add -A && git commit -m "test tower Job ID {{ tower_job_id }}: Automated Commit by Ansible  " && git push
      