---
- name: show interface
  hosts: cs01
  gather_facts: false
  become: yes
  
  tasks:
    - name: show interface of cs01
      ios_command:
        commands: show interfaces {{ interface }}
      register: result

    - debug:
        var: result

    - name: Save variable result to file
      copy:
        content: "{{ result }}"
        dest: "./file/result.txt"
    
    - name: display folder
      ansible.builtin.shell: |
        cd file 
        ls
      register: result

    - debug:
        var: result 

    - name: Test Git Command
      ansible.builtin.shell:
        cmd: "git status"
        chdir: "./"
      register: git_status

    - debug:
        var: git_status.stdout_lines    

    - name: set name
      ansible.builtin.shell:
        cmd: git config --global user.name "faya97"

    - name: Set email
      ansible.builtin.shell:
        cmd: git config --global user.email "chaneric762@gmail.com"

    - name: git add
      ansible.builtin.shell:
        cmd: git add -A
    
    - name: Commit Changes
      git:
        repo: ./
        msg: "Commit message describing the changes"
    
    - name: Push Changes
      git:
        repo: ./
      
      