---
- name: show interface
  hosts: cs01
  gather_facts: false
  become: yes
  
  tasks:
    - name: show interface of cs01
      ios_command:
        commands: show interfaces {{ interface }}
      register: result

    - debug:
        var: result

    - name: Save variable result to file
      copy:
        content: "{{ result }}"
        dest: "/var/lib/awx/projects/_9__ansible_lab_2/file/result.txt"
      delegate_to: localhost