---
- name: show role path
  hosts: cs01
  roles: 
    - new_role2

  tasks:

    - name: display folder
      ansible.builtin.shell: |
        cd ./roles/new_role2/files
        ls
      register: result

    - debug:
        var: result 

    - name: injection of the configuration
      ios_config:
        src: "./files/port.set"
      