---

- name: check vyos system
  hosts: spine01
  gather_facts: false

  tasks:
    - name: commands for vyos
      vyos_command:
        commands:
          - sh host date
          - sh host domain
          - sh host name
          - sh host os
      register: vyos_facts
    
    - debug:
        msg: "vyos fact : {{ vyos_facts }}"
