---


- name: check vyos system
  hosts: vyos_group
  gather_facts: false

  tasks:
    - name: commands for vyos
      vyos_command:
        commands:
          - sh host date
          - sh host domain
          - sh host name
          - sh host os
      result: vyos_facts
    
    - debug:
        msg: "vyos fact : {{ vyos_facts }}"
