---
- name: 'Explicit host argument'
  hosts: junos
#  connection: local
  connection: juniper.device.pyez

  gather_facts: no
  collections:
    - juniper.device

  vars:
    host: 10.x.x.x
    user: user
    passwd: user123
    timeout: 300

# The example here uses vars for user-authentication.

  tasks:
    # Command module executed
    - name: show version with command
      command:
        commands:
          - "show version"
      register: response

    - name: "Print the response"
      debug:
        var: response

    # Rpc module executed
    - name: "Test RPC"
      rpc:
        rpcs:
          - "get-config"
          - "get-software-information"

# close connection
