- name: 'Explicit host argument'
  hosts: junos
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Reboot all REs of the device
      system:
        action: "reboot"

    - name: Power off the other RE of the device.
      system:
        action: "shutdown"
        othe_re: True

    - name: Reboot this RE at 8pm today.
      system:
        action: "reboot"
        all_re: False
        at: "20:00"

    - name: Halt the system on 25 January 2018 at 4pm.
      system:
        action: "halt"
        at: "1801251600"

    - name: Reboot the system in 30 minutes.
      system:
        action: "reboot"
        in_min: 30

    - name: Reboot the system in 30 minutes.
      system:
        action: "reboot"
        at: "+30m"

    - name: Zeroize the local RE only.
      system:
        action: "zeroize"
        all_re: False

    - name: Zeroize all REs and overwrite medea.
      system:
        action: "zeroize"
        media: True
