---
# tasks file for new_role
- name: display message from myrole
  debug:
    msg: display from myrole2

- name: create configuration file
  template: src=shutdown.j2 dest={{path_files}}/port_{{ inventory_hostname }}.set
  tags: role2